name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium pytest-cov

      - name: Start Flask server in the background
        run: |
          nohup flask run &  
      - name: Wait for Flask server to start
        run: |
          sleep 5  

      - name: Run Selenium tests
        run: |
          pytest tests/test_app_integration.py --maxfail=1 --disable-warnings -q
