name: Codecov Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12.5
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.5"

      - name: Verify Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov codecov
          pip install selenium

      - name: Run tests with coverage
        run: pytest --cov=. tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: unittests

      - name: Start Flask server in the background
        run: |
          nohup flask run &  

      - name: Wait for Flask server to start
        run: |
          sleep 5  

      - name: Run Selenium tests
        run: |
          pytest tests/test_app_integration.py --maxfail=1 --disable-warnings -q
