name: Automatic Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.5
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.5'

      - name: Verify Python version
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Start Flask server in the background
        run: |
          nohup python app.py &

      - name: Wait for Flask server to start
        run: |
          sleep 5  

      - name: Run Selenium tests
        run: |
          pytest tests/test_app_integration.py