name: Automatic Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ou a versão que você usa no seu projeto

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Instala as dependências do seu projeto

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Executa os testes
